export default {
    CHANGE_ALL_MV:"CHANGE_ALL_MV",
    CHANGE_MV_URL_LIST:"CHANGE_MV_URL_LIST",
    CHANGE_SINGER_PIC:"CHANGE_SINGER_PIC",
    CHANGE_SINGER_PIC1:"CHANGE_SINGER_PIC1",
    CHANGE_MV_LIKE:"CHANGE_MV_LIKE",
    CHANGE_MV_COMMENT:"CHANGE_MV_COMMENT",
    CHANGE_MV_RANK_LIST:"CHANGE_MV_RANK_LIST",
    CHANGE_MV_DETAILS:"CHANGE_MV_DETAILS",
    CHANGE_MV_BRS:"CHANGE_MV_BRS",
    CHANGE_RELATED_VIDEOS:"CHANGE_RELATED_VIDEOS",
    CHANGE_MV_COMMENTS:"CHANGE_MV_COMMENTS",
    CHANGE_VIDEO_DETAILS:"CHANGE_VIDEO_DETAILS"
}