export default {
    CHANGE_ALL_MV:"CHANGE_ALL_MV",
    CHANGE_MV_URL_LIST:"CHANGE_MV_URL_LIST",
    CHANGE_SINGER_PIC:"CHANGE_SINGER_PIC",
    CHANGE_MV_LIKE:"CHANGE_MV_LIKE",
    CHANGE_MV_COMMENT:"CHANGE_MV_COMMENT",
    CHANGE_MV_RANK_LIST:"CHANGE_MV_RANK_LIST"
}