export default {
    CHANGE_HOT_LIST:"CHANGE_HOT_LIST",
    CHANGE_FUZZY_SEARCH_LIST:"CHANGE_FUZZY_SEARCH_LIST",
    CHANGE_COMPOSITE_LIST:"CHANGE_COMPOSITE_LIST",
    CHANGE_SINGLE_LIST:"CHANGE_SINGLE_LIST",
    CHANGE_VIDEO_LIST:"CHANGE_VIDEO_LIST",
    CHANGE_SONG_WRITER_LIST:"CHANGE_SONG_WRITER_LIST",
    CHANGE_ALBUM_LIST:"CHANGE_ALBUM_LIST",
    CHANGE_PLAY_LIST:"CHANGE_PLAY_LIST",
    CHANGE_RADIO_STATION_LIST:"CHANGE_RADIO_STATION_LIST",
    CHANGE_USER_HOME_LIST:"CHANGE_USER_HOME_LIST",
    CHANGE_USER_INFO_LIST:"CHANGE_USER_INFO_LIST"
}