export default {
    hotList:[],
    fuzzySearchList:[],
    compositeList:[],
    singleList:[],
    videoList:[],
    songWriterList:[],
    albumList:[],
    playList:[],
    radioStationList:[],
    uerHomeList:[],
    userInfoList: [],
    userPlayList:[],
    userPlayListTow:[],
}