export default {
    CHANGE_CYPLAY_LIST:"CHANGE_CYPLAY_LIST",
    CHANGE_CYRECORD:"CHANGE_CYRECORD",
    CHANGE_CYSUBCOUNT:"CHANGE_CYSUBCOUNT",
    CHANGE_CYPLAY_LIST_DETAIL:"CHANGE_CYPLAY_LIST_DETAIL",
    CHANGE_SON_DETAIL:"CHANGE_SON_DETAIL",
    CHANGE_MUSIC:"CHANGE_MUSIC"
}