import React from 'react'
class Find extends React.Component{
    render(){
        return(
            <div>
                <div>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                    <p>发现</p>
                </div>
            </div>
        )
    }
}
export default Find;