export default {
    CHANGE_BANNERS:"CHANGE_BANNERS",
    CHANGE_INTRO_PLAY_LIST:"CHANGE_INTRO_PLAY_LIST",
    CHANGE_NEW_SONG:"CHANGE_NEW_SONG",
    CHANGE_SEL_MV:"CHANGE_SEL_MV",
    CHANGE_MV_LIST:"CHANGE_MV_LIST"
}