export default {
    CHANGE_BANNERS:"CHANGE_BANNERS",
    CHANGE_INTRO_PLAY_LIST:"CHANGE_INTRO_PLAY_LIST",
    CHANGE_NEW_SONG:"CHANGE_NEW_SONG",
    CHANGE_SEL_MV:"CHANGE_SEL_MV",
    CHANGE_MV_LIST:"CHANGE_MV_LIST",
    CHANGE_RECOMMEND_SONGS:"CHANGE_RECOMMEND_SONGS",
    CHANGE_SONG_LIST_BANNER:"CHANGE_SONG_LIST_BANNER",
    CHANGE_SONG_LIST_INTRO:"CHANGE_SONG_LIST_INTRO",
    CHANGE_SONG_LIST_OTHER:"CHANGE_SONG_LIST_OTHER",
    CHANGE_REWARD_TOP_LIST:"CHANGE_REWARD_TOP_LIST",
    CHANGE_TOP_LIST:"CHANGE_TOP_LIST",
    CHANGE_LIST_OTHERS:"CHANGE_LIST_OTHERS"
}